### PR TITLE
Make help more helpful

### LINKED ISSUE #45: Improve no-argument output
Currently, something like `bundle exec crep crashes` or even `bundle exec crep crashes --help` crashes with not the most beautiful nor helpful message:

```
/crep/lib/crep/command/crashes.rb:30:in `initialize': Missing `identifier` parameter (RuntimeError)
	from /.rvm/gems/ruby-2.3.1/gems/claide-1.0.2/lib/claide/command.rb:356:in `new'
	from /.rvm/gems/ruby-2.3.1/gems/claide-1.0.2/lib/claide/command.rb:356:in `parse'
	from /.rvm/gems/ruby-2.3.1/gems/claide-1.0.2/lib/claide/command.rb:352:in `parse'
	from /.rvm/gems/ruby-2.3.1/gems/claide-1.0.2/lib/claide/command.rb:330:in `run'
	from /crep/lib/crep.rb:13:in `run'
	from /crep/bin/crep:7:in `<top (required)>'
	from /.rvm/gems/ruby-2.3.1/bin/crep:23:in `load'
	from /.rvm/gems/ruby-2.3.1/bin/crep:23:in `<main>'
	from /.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

This should be improved; it should point the user to an example or missing arguments.

### PR DESCRIPTION
**Pull request by q231950**
This pr will make the help output more helpful and prevent unintended runs of the _crashes_ command.
Fixes #45

### CODE REVIEW

File: lib/crep/command/crashes.rb [hunk 1]
```diff
@@ -22,16 +22,25 @@ def self.options
...
       @top = argv.option('top') || DEFAULT_TOP_COUNT
-      @bundle_identifier = argv.option('identifier') || raise('Missing `identifier` parameter')
-      @version = argv.option('version') || raise('Missing `version` parameter')
-      @build = argv.option('build') || raise('Missing `build` parameter')
+      @bundle_identifier = argv.option('identifier')
+      @version = argv.option('version')
+      @build = argv.option('build')
+    end
+
+    def validate!
```
Comment (JoeSSS) [inline lib/crep/command/crashes.rb]: Why validate is (!) ? doesn't seem that it changes smth. 
Also, where is validate used?

Comment (q231950) [reply lib/crep/command/crashes.rb]: It's coming from the parent class of [CLAide](https://github.com/CocoaPods/CLAide/blob/master/lib/claide/command.rb#L22). It get's called automatically by CLAide and it's our hook to tell it that we want to validate something.

Comment (JoeSSS) [reply lib/crep/command/crashes.rb]: Weird syntax, but if it is not ours than 👍 :)

**Comment by q231950** [comment]
Thank you @BasThomas @JoeSSS : )
