### PR TITLE
34 add templates

### LINKED ISSUE #34: Add support for newsletter templates
We should be able to create a template that gets filled by `Crep` and creates a newsletter from the crash input.

### PR DESCRIPTION
**Pull request by jamuc**
Fixes #34 
I think I would also like to extend the pull request so that the used template is configurable.

### CODE REVIEW

File: lib/crep/crash_controller.rb [hunk 1]
```diff
@@ -24,42 +27,21 @@ def top_crashes(version, build)
...
+      b.local_variable_set(:crashes, crashes)
+      b.local_variable_set(:app_name, app_name)
+      b.local_variable_set(:version, version)
+      b.local_variable_set(:build, build)
+      b.local_variable_set(:identifier, identifier)
+      b.local_variable_set(:total_crashes, total_crashes)
+      template = File.read DEFAULT_REPORT
+      renderer = ERB.new template
+      puts output = renderer.result(b)
+      output
```
Comment (jamuc) [inline lib/crep/crash_controller.rb]: @q231950 This was why the diff was empty. When you run puts it returns a nil. Still couldn't get the test case to work though. It's because the ERB returns a slightly different representation than ```File.read```.  
I also tried to write the test output to a file and then read it again. Then it's nearly exactly the same except that for some reason an extra new line is added to the end of the string. Giving up for today.

Comment (jamuc) [reply lib/crep/crash_controller.rb]: Hm, standing up and walking around provided the solution. Add a newline in the fixtures. The test seems to have passed but danger still marked this as failed?

File: spec/crash_controller_spec.rb [hunk 2]
```diff
@@ -4,88 +4,36 @@
...
-      allow(@crash_source).to receive(:crashes).and_return([crash_instance, crash_instance_2])
-      allow(@crash_source).to receive(:crash_count).and_return(150)
-      allow(@crash_source).to receive(:app)
-      allow(@crash_source.app).to receive(:name).and_return('app_name')
-      allow(@crash_source.app).to receive(:bundle_identifier).and_return('bundle.id')
-    end
-
     it 'should output the result based on class variables' do
-      output = subject.new.top_crashes('0.1.19', 1114)
+      output = subject.top_crashes('0.1.19', 1114)
```
Comment (jamuc) [inline spec/crash_controller_spec.rb]: @q231950 Alright, the last commit might have been a bit too much.  I wanted to see how much I could simplify the code to make everything more readable again. Incidentally, writing stuff using as little code as possible is considered best practice in ruby :)
If I cut too much, we can always revert the commit. Right, got to leave

File: lib/crep/crash_controller.rb [hunk 3]
```diff
@@ -1,65 +1,39 @@
 require 'colorize'
+require 'erb'
+require 'pry'
```
Comment (q231950) [inline lib/crep/crash_controller.rb]: Please remove the _require_

File: spec/crash_controller_spec.rb [hunk 4]
```diff
@@ -4,219 +4,37 @@
...
-                                'Percentage: 33.33% of all 0.0.1 crashes',
-                                'File/Line: line:123',
-                                'Reason: Unknown',
-                                expected_link,
-                                "Deep Link: #{deep_link}"
-                              ]
-                            ])
-    end
+  let(:app) { instance_double('Crep::App', name: 'app_name', bundle_identifier: 'bundle.id') }
+  let(:crash_source) { instance_double('Crep::HockerAppCrashSource', crashes: [crash_instance, crash_instance_2], crash_count: 150, app: app, configure: nil) }
```
Comment (q231950) [inline spec/crash_controller_spec.rb]: Please rename `HockerAppCrashSource` to `HockeyAppCrashSource`

**Comment by q231950** [comment]
@jamuc The bot is not happy because the fixtures have been modified. I would suggest that I merge this with failure because the failure is incorrect in this case. Are you ok with that?

**Comment by q231950** [comment]
@jamuc actually we could adapt:

```
Reporting for YourApp (0.17.1/1114) your.bundle.identifier
------------- #1 --------------
```

```
Reporting for YourApp (0.17.1/1114) your.bundle.identifier

------------- #1 --------------
```
