### PR TITLE
Initial `apps` command

### LINKED ISSUE #62: Add `Apps` command
In the past we found that sometimes it is cumbersome to find the right app to create a crash report for.

**Crep** should have a way to show a list of apps matching a version or parts of a version.

### PR DESCRIPTION
**Pull request by q231950**
Adds a new command, `crep apps` to **Crep**. Fixes #62.

Supported parameters:
```
--identifier=<com.company.app>', 'Crep will show app information with this identifier'
--version=<7.10.0>', 'An optional filter for the version of an app.'
--build=<24>', 'An optional filter for the build of an App.'
--versions=5', "If set, Crep will limit the number of displayed versions per app.
```

The command allows for explorative search for versions like 
`bundle exec crep apps --version=7.12.0  --versions=3` 
to very specific ones like
`bundle exec crep apps --identifier='com.abc.dev' --build=11016 --versions=3`

```
[INFO] 2018-02-03 11:22:18 +0100: Reporting apps:

		ABC
		7.14.0 (10049)
		7.14.0 (10046)
		7.13.1 (10045)
		7.13.1 (10043)
		7.13.0 (10041)

		ABC Alpha
		7.15.0 (11038)
		7.15.0 (11036)
		7.15.0 (11035)
		7.15.0 (11034)
		7.15.0 (11033)

		ABC Beta
		7.14.0 (1431)
		7.14.0 (1428)
		7.14.0 (1427)
		7.13.1 (1426)
		7.13.1 (1425)
```

### CODE REVIEW

**Comment by q231950** [comment]
@BasThomas @dhartwich1991 @JoeSSS one of you wants to volunteer for a review of this? No hurry 😌

This is pretty big already and I'd like to add some tests in another pull request.

File: lib/crep/command/apps.rb [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+      DESC
+
+    def initialize(argv)
+      super
+
+      @versions_limit = argv.option('versions') || DEFAULT_VERSIONS_LIMIT
+      CrepLogger.info("Versions will be limited to #{ @versions_limit } per app")
+
+      @identifier = argv.option('identifier')
+      CrepLogger.info("Apps will be filtered by identifier: #{ @identifier }") unless !@identifier
```
Comment (JoeSSS) [inline lib/crep/command/apps.rb]: Why not just if? :)

File: lib/crep/app_controller.rb [hunk 2]
```diff
@@ -0,0 +1,34 @@
+module Crep
+    class AppController
+
+        def initialize(app_source, identifier, version, build, versions_limit)
+          @identifier = identifier ? identifier.downcase : nil
```
Comment (JoeSSS) [inline lib/crep/app_controller.rb]: indentation is a bit broken here

Comment (JoeSSS) [reply lib/crep/app_controller.rb]: Can be changed to: `@identifier = identifier&.downcase`

File: lib/crep/app_controller.rb [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+
+            @app_source = app_source
+            @app_source.configure()
+        end
+        
+        def apps
+          filtered_apps = @app_source.apps.select do | app |
+            @identifier ? app.bundle_identifier.downcase == @identifier : true
+          end
+            filtered_apps.each do | app |
```
Comment (JoeSSS) [inline lib/crep/app_controller.rb]: please fix indendation

File: lib/crep/command/apps.rb [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+      
+      @version = argv.option('version')
+      CrepLogger.info("Version will be filtered: #{ @version }") unless !@version
```
Comment (JoeSSS) [inline lib/crep/command/apps.rb]: same as previous

File: lib/crep/command/apps.rb [hunk 5]
```diff
@@ -0,0 +1,51 @@
...
+
+      @build = argv.option('build')
+      CrepLogger.info("Build will be filtered: #{ @build }") unless !@build
```
Comment (JoeSSS) [inline lib/crep/command/apps.rb]: same as previous

File: lib/crep/model/app_source/hockeyapp_app_source.rb [hunk 6]
```diff
@@ -0,0 +1,33 @@
...
+      HockeyApp::Config.configure do |config|
+        raise 'Missing API token (CREP_HOCKEY_API_TOKEN)' unless ENV['CREP_HOCKEY_API_TOKEN']
+        config.token = ENV['CREP_HOCKEY_API_TOKEN']
+      end
+
+      @client = HockeyApp.build_client
+    end
+
+    def apps
+      @client.get_apps.map do |app|
```
Comment (JoeSSS) [inline lib/crep/model/app_source/hockeyapp_app_source.rb]: Should be possible to change to an one-liner:
`@client.get_apps.map { |app| app }`

File: lib/crep/model/app_source/hockeyapp_app_source.rb [hunk 7]
```diff
@@ -0,0 +1,33 @@
...
+        app
+      end
+    end
+
+    def versions(app, version, build, limit)
+      filtered_versions = app.versions.select do | v |
+        version_match = version ? v.shortversion == version : true
+        build_match = build ? v.version == build : true
+        version_match && build_match
```
Comment (JoeSSS) [inline lib/crep/model/app_source/hockeyapp_app_source.rb]: Seems like we don't use build_match anywhere

File: lib/crep/model/app_source/hockeyapp_app_source.rb [hunk 8]
```diff
@@ -0,0 +1,33 @@
...
+      end
+
+      filtered_versions.first(limit).map do | v |
```
Comment (JoeSSS) [inline lib/crep/model/app_source/hockeyapp_app_source.rb]: Why .first here? Is it an array of arrays?

Comment (q231950) [reply lib/crep/model/app_source/hockeyapp_app_source.rb]: It returns an array with the first n elements of the `filtered_versions`.

Comment (JoeSSS) [reply lib/crep/model/app_source/hockeyapp_app_source.rb]: Ah, cool! Didn't know that first can get parameters :)

File: lib/crep/model/app_source/hockeyapp_app_source.rb (hunk 6 above)
Comment (q231950) [reply lib/crep/model/app_source/hockeyapp_app_source.rb]: I think the mapping should be removed completely since it doesn't do anything 😮

https://github.com/xing/crep/blob/06d7d5ec7603b85a7b271c5577512dc755635fab/lib/crep/model/app_source/hockeyapp_app_source.rb#L16-L18

File: lib/crep/app_controller.rb (hunk 2 above)
Comment (q231950) [reply lib/crep/app_controller.rb]: This is really cool, had to search a bit until I found out that this is a _safe navigation operator_.

https://stackoverflow.com/a/34626154
http://mitrev.net/ruby/2015/11/13/the-operator-in-ruby/

**Comment by q231950** [comment]
@JoeSSS I noticed that once I do the filtering of apps and versions in two different places. I think I should get this right. 

Currently filtering of apps happens in the App Controller whereas filtering of the versions happens inside the HockeyApp Source. I will move the all filtering into the App Controller.

File: lib/crep/command/apps.rb [hunk 9]
```diff
@@ -0,0 +1,53 @@
...
+require 'crep/command'
+require 'crep/app_controller'
+require 'crep/model/app_source/hockeyapp_app_source'
+
+module Crep
+  class Apps < Command
+    # options should accept app name and version filter
+    DEFAULT_VERSIONS_LIMIT = 5
+
+    def self.options
```
Comment (BasThomas) [inline lib/crep/command/apps.rb]: We should evaluate if we want to have the `<>`s around the parameters. We should at least be consistent. Or is it intended for `versions` to not have the brackets because it is a default value?

File: lib/crep/command/apps.rb [hunk 10]
```diff
@@ -0,0 +1,53 @@
...
+      [
+        ['--identifier=<com.company.app>', 'Crep will show app information with this identifier'],
+        ['--version=<7.10.0>', 'An optional filter for the version of an app.'],
+        ['--build=<24>', 'An optional filter for the build of an App.'],
+        ['--versions=5', "If set, Crep will limit the number of displayed versions per app. #{DEFAULT_VERSIONS_LIMIT} by default."]
+      ].concat(super)
+    end
+
+    self.summary = <<-DESC
+          Shows the apps with their versions available for the current API token
```
Comment (BasThomas) [inline lib/crep/command/apps.rb]: Nit: end with a `.`.

Comment (BasThomas) [reply lib/crep/command/apps.rb]: Also, do we need to mention that this needs a token?

File: lib/crep/command/apps.rb [hunk 11]
```diff
@@ -0,0 +1,53 @@
...
+      DESC
+
+    self.description = <<-DESC
+        Shows apps with their versions. The CREP_HOCKEY_API_TOKEN needs to be set.
```
Comment (BasThomas) [inline lib/crep/command/apps.rb]: We should not mention Hockey directly here; it could be another source as well.

File: lib/crep/command/apps.rb [hunk 12]
```diff
@@ -0,0 +1,53 @@
...
+
+      @version = argv.option('version')
+      CrepLogger.info("Version will be filtered: #{@version}") if @version
+
+      @build = argv.option('build')
+      CrepLogger.info("Build will be filtered: #{@build}") if @build
+    end
+
+    def run
+      CrepLogger.info('Reporting apps:')
```
Comment (BasThomas) [inline lib/crep/command/apps.rb]: From your example, it seems like this is printed even without `--verbose`. Is that intended?

File: lib/crep/command/apps.rb [hunk 13]
```diff
@@ -0,0 +1,53 @@
...
+
+      app_source = HockeyAppAppSource.new
```
Comment (BasThomas) [inline lib/crep/command/apps.rb]: Why do we initialize a new (Hockey) App Source here?

File: lib/crep/model/app_source/hockeyapp_app_source.rb [hunk 14]
```diff
@@ -0,0 +1,33 @@
+# frozen_string_literal: true
+
+require 'crep/model/app_source/app_source'
+require 'hockeyapp'
+
+module Crep
+  class HockeyAppAppSource < AppSource
+    def configure
+      HockeyApp::Config.configure do |config|
+        raise 'Missing API token (CREP_HOCKEY_API_TOKEN)' unless ENV['CREP_HOCKEY_API_TOKEN']
```
Comment (BasThomas) [inline lib/crep/model/app_source/hockeyapp_app_source.rb]: Maybe we should keep one instance of this `CREP_HOCKEY_API_TOKEN` String and reuse it? 😁

File: lib/crep/command/apps.rb (hunk 12 above)
Comment (q231950) [reply lib/crep/command/apps.rb]: I didn't even think about it. I'll add a verbose flag 🙂

File: lib/crep/command/apps.rb (hunk 13 above)
Comment (q231950) [reply lib/crep/command/apps.rb]: Like this we can pass in _any_ app source into the app controller. Since we only have hockeyapp support right now, there is no mechanism in place that selects the right app source. I think that mechanism would better explain why we pass it in. 

Passing it in from the outside also makes it easier to mock the source. But you are reminding me of making the app controller independent from _hockeyapp_.

File: lib/crep/model/app_source/hockeyapp_app_source.rb (hunk 14 above)
Comment (q231950) [reply lib/crep/model/app_source/hockeyapp_app_source.rb]: We do the setup of the hockeyapp client in the crash source as well as the app source - we could think about extracting it. I'd do so in a separate pr though and right now it's still ok with the 2 occurrences, I think.

File: lib/crep/command/apps.rb (hunk 9 above)
Comment (BasThomas) [reply lib/crep/command/apps.rb]: We should followup in a future pull request to clean up [`apps.rb`](https://github.com/xing/crep/blob/master/lib/crep/command/crashes.rb#L12-L16) too, then.
